# Generated by Django 2.2.2 on 2019-07-01 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cities',
            name='city',
            field=models.ImageField(upload_to='gallery'),
        ),
    ]
