# Generated by Django 2.2.2 on 2019-07-01 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20190701_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cities',
            name='city',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
